Improve docstrings
pmem/pmemkv-python pull request #25
Opened 2020-01-29 11:24 UTC by karczex

2020-01-29 11:49 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/25)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @karczex)

___
*[pmemkv/kvengine.cc, line 58 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/25#-Lzl7NJi8k4aU7npRIzN:-Lzl7NJi8k4aU7npRIzO:blwidri) ([raw file](https://github.com/pmem/pmemkv-python/blob/573389f9016a27d74fee0a89b820ba62f406fb26/pmemkv/kvengine.cc#L58)):*
> ```cpp
> 	{PMEMKV_STATUS_UNKNOWN_ERROR,
> 	 Exception{NULL, "UnknownError", "pmemkv_NI.UnknownError",
> 		   "Something unexpected went wrong"}},
> ```

This sounds strange, maybe "Something unexpected happened"?
___
*[pmemkv/kvengine.cc, line 60 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/25#-Lzl7BhV75Awa6DKvdn5:-Lzl7BhV75Awa6DKvdn6:b-nhw7lg) ([raw file](https://github.com/pmem/pmemkv-python/blob/573389f9016a27d74fee0a89b820ba62f406fb26/pmemkv/kvengine.cc#L60)):*
> ```cpp
> 		   "Something unexpected went wrong"}},
> 	{PMEMKV_STATUS_NOT_FOUND,
> 	 Exception{PyExc_KeyError, NULL, NULL, "Record (or config item) not found"}},
> ```

Make it more clear that record is a database record (maybe write "Database record/entry")
___
*[pmemkv/kvengine.cc, line 75 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/25#-Lzl6qPK4NGSWqXRI_zL:-Lzl6qPK4NGSWqXRI_zM:b4aqwi8) ([raw file](https://github.com/pmem/pmemkv-python/blob/573389f9016a27d74fee0a89b820ba62f406fb26/pmemkv/kvengine.cc#L75)):*
> ```cpp
> 	{PMEMKV_STATUS_STOPPED_BY_CB,
> 	 Exception{NULL, "StoppedByCallback", "pmemkv_NI.StoppedByCallback",
> 		   "Callback function aborted in unexpected way"}},
> ```

unexpected? it was probably aborted because of user exception
___
*[pmemkv/kvengine.cc, line 85 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/25#-Lzl6zfY-4iwUcJLcsR7:-Lzl6zfY-4iwUcJLcsR8:bf6980l) ([raw file](https://github.com/pmem/pmemkv-python/blob/573389f9016a27d74fee0a89b820ba62f406fb26/pmemkv/kvengine.cc#L85)):*
> ```cpp
> 	{PMEMKV_STATUS_TRANSACTION_SCOPE_ERROR,
> 	 Exception{NULL, "TransactionScopeError", "pmemkv_NI.TransactionScopeError",
> 		   "An error with the scope of the libpmemobj transaction"}}};
> ```

Hm, not really connected to this PR, but this status can't really be returned to Python (you cannot start a pmemobj transaction in python).


<!-- Sent from Reviewable.io -->

2020-01-29 11:56 UTC, karczex commented
___
*[pmemkv/kvengine.cc, line 75 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/25#-Lzl6qPK4NGSWqXRI_zL:-Lzl8cy_-aCXR40HgLkh:b-2n7v98) ([raw file](https://github.com/pmem/pmemkv-python/blob/573389f9016a27d74fee0a89b820ba62f406fb26/pmemkv/kvengine.cc#L75)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

unexpected? it was probably aborted because of user exception
</blockquote></details>

User exception is forwarded. This is situation, when user exception was not thrown, but PMEMKV_STATUS_STOPPED_BY_CB was returned by from pmemkv. 


<!-- Sent from Reviewable.io -->

2020-01-29 13:34 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/25)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @igchor)

___
*[pmemkv/kvengine.cc, line 58 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/25#-Lzl7NJi8k4aU7npRIzN:-LzlUGbtEp84mCN2XLRH:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/573389f9016a27d74fee0a89b820ba62f406fb26/pmemkv/kvengine.cc#L58)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

This sounds strange, maybe "Something unexpected happened"?
</blockquote></details>

Done.
___
*[pmemkv/kvengine.cc, line 60 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/25#-Lzl7BhV75Awa6DKvdn5:-LzlU9Vs8ZeVm9QE90dI:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/573389f9016a27d74fee0a89b820ba62f406fb26/pmemkv/kvengine.cc#L60)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Make it more clear that record is a database record (maybe write "Database record/entry")
</blockquote></details>

Done.
___
*[pmemkv/kvengine.cc, line 85 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/25#-Lzl6zfY-4iwUcJLcsR7:-LzlTbc78FMBY1W0Sd7R:b-b9wbwj) ([raw file](https://github.com/pmem/pmemkv-python/blob/573389f9016a27d74fee0a89b820ba62f406fb26/pmemkv/kvengine.cc#L85)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, not really connected to this PR, but this status can't really be returned to Python (you cannot start a pmemobj transaction in python).
</blockquote></details>

If you are really want to, you are able to do it :) 
I left it for API compatibility. Little extended.   


<!-- Sent from Reviewable.io -->

2020-02-03 11:51 UTC, igchor requested changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/25)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @karczex)

___
*[pmemkv/pmemkv.py, line 45 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-9sTj72pumFmeYGY0p:-M-9sTj72pumFmeYGY0q:br3s491) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/pmemkv.py#L45)):*
> ```Python
>             Engine Name of the engine to work with.
>         config : dict
>             Dictionary with parameters specified for the engine.
> ```

maybe some reference to manpage where all those parameters are described?
___
*[pmemkv/pmemkv.py, line 88 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-9sKrZ0FfzLKGadeJj:-M-9sKrZ0FfzLKGadeJk:b-o0k5y) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/pmemkv.py#L88)):*
> ```Python
>         Parameters
>         ----------
>         key: str
> ```

why not also "or byte-like object"?
___
*[pmemkv/pmemkv.py, line 309 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-9spyaB45Owrnn4B27:-M-9spyaB45Owrnn4B28:bisdss7) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/pmemkv.py#L309)):*
> ```Python
>             Function to be called for specified element. Value passed to func
>             is read only buffer, and may be accessed by memoryview function.
>             Callback function should one argument.
> ```

should **take** one argument?


<!-- Sent from Reviewable.io -->

2020-02-03 11:56 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/25)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @karczex)

___
*[pmemkv/pmemkv.py, line 115 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-9tAtWE7WW-X3gd_ZK:-M-9tAtWE7WW-X3gd_ZL:bqf2jg5) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/pmemkv.py#L115)):*
> ```Python
>         Parameters
>         ----------
>         key : str
> ```

Please add info how strings are converted to binary data (and that the comparison works on binary data)


<!-- Sent from Reviewable.io -->

2020-02-03 14:36 UTC, lukaszstolarczuk requested changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/25)* status: all files reviewed, 31 unresolved discussions (waiting on @igchor and @karczex)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-ATXwo7IZnba4YoH_k:-M-ATXwp7AUwe_aCXLmv:baq4dws) (no related file):*
1. commit message:
- parameters (lowercase)
- compliant (typo)

2. commit message:
- to be **the best** solution
- **the** creation

---
___
*[pmemkv/kvengine.cc, line 58 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-AM4uvEcW1SSzGnAF0:-M-AM4uvEcW1SSzGnAF1:b-nzzehv) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/kvengine.cc#L58)):*
> ```cpp
> 	{PMEMKV_STATUS_UNKNOWN_ERROR,
> 	 Exception{NULL, "UnknownError", "pmemkv_NI.UnknownError",
> 		   "Something unexpected heppened"}},
> ```

happend
___
*[pmemkv/kvengine.cc, line 76 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-AMgJf5-ZCUkQ08jbc:-M-AMgJf5-ZCUkQ08jbd:b-pz0zwf) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/kvengine.cc#L76)):*
> ```cpp
> 	{PMEMKV_STATUS_STOPPED_BY_CB,
> 	 Exception{NULL, "StoppedByCallback", "pmemkv_NI.StoppedByCallback",
> 		   "Callback function aborted in unexpected way"}},
> ```

1. is it an unexpected way?  compare with https://pmem.io/pmemkv/master/manpages/libpmemkv.3.html
2. in **an** unexp..
___
*[pmemkv/kvengine.cc, line 88 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-AN4xLA-Yn9Mw_pyC6:-M-AN4xM5cadG7YBzTMi:b-h6ks4g) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/kvengine.cc#L88)):*
> ```cpp
> 		 NULL, "TransactionScopeError", "pmemkv_NI.TransactionScopeError",
> 		 "An error with the scope of the libpmemobj transaction. This exception is defined for compatibility with pmemkv API and probably will never occur"}},
> };
> ```

I guess we don't implement defrag func. yet...? (we're missing here one status from the latest release)
___
*[pmemkv/pmemkv.py, line 43 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-AOarnECwmxJ8sQP7W:-M-AOarnECwmxJ8sQP7X:b567hyo) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/pmemkv.py#L43)):*
> ```Python
>         ----------
>         engine: str
>             Engine Name of the engine to work with.
> ```

**n**ame (lowercase)
___
*[pmemkv/pmemkv.py, line 44 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-AOh445KbNku457V2M:-M-AOh445KbNku457V2N:bszni3d) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/pmemkv.py#L44)):*
> ```Python
>         engine: str
>             Engine Name of the engine to work with.
>         config : dict
> ```

confi**g:** ... (no space)
___
*[pmemkv/pmemkv.py, line 101 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-AP8FS08yQK8x0czhZ:-M-AP8FS08yQK8x0czh_:b-jkfj9r) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/pmemkv.py#L101)):*
> ```Python
>         Parameters
>         ----------
>         func : function (may be lambda)
> ```

. (no space)
___
*[pmemkv/pmemkv.py, line 102 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-APEdlEM7_8UkoIvsf:-M-APEdlEM7_8UkoIvsg:b-ou8q02) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/pmemkv.py#L102)):*
> ```Python
>         ----------
>         func : function (may be lambda)
>             Function to be called for each element. Key passed to func is read
> ```

read**-**only
___
*[pmemkv/pmemkv.py, line 102 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-AQqXL7NU-mFQxwvaQ:-M-AQqXL7NU-mFQxwvaR:bwj49b2) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/pmemkv.py#L102)):*
> ```Python
>         ----------
>         func : function (may be lambda)
>             Function to be called for each element. Key passed to func is read
> ```

for each **key** (instead of 'element')
___
*[pmemkv/pmemkv.py, line 103 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-APLOG01Zd-z3utBuF:-M-APLOG01Zd-z3utBuG:b275hvd) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/pmemkv.py#L103)):*
> ```Python
>         func : function (may be lambda)
>             Function to be called for each element. Key passed to func is read
>             only buffer, and may be accessed by memoryview function, Callback
> ```

function**.** (full stop instead of comma)
___
*[pmemkv/pmemkv.py, line 103 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-ASEBL-YQpThPtp3sp:-M-ASEBM2cZzIhzfn1WN:b-z7yx5b) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/pmemkv.py#L103)):*
> ```Python
>         func : function (may be lambda)
>             Function to be called for each element. Key passed to func is read
>             only buffer, and may be accessed by memoryview function, Callback
> ```

no comma before "and"
___
*[pmemkv/pmemkv.py, line 104 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-APPMB4Zru8phmYRC5:-M-APPMB4Zru8phmYRC6:b768yzj) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/pmemkv.py#L104)):*
> ```Python
>             Function to be called for each element. Key passed to func is read
>             only buffer, and may be accessed by memoryview function, Callback
>             function should acceppt one argument.
> ```

1. accept (typo)
2. "one argument" - what argument?
___
*[pmemkv/pmemkv.py, line 115 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-APcJOCMTiqORhQPiT:-M-APcJP6aqxzH222AWt:b-fvh4yi) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/pmemkv.py#L115)):*
> ```Python
>         Parameters
>         ----------
>         key : str
> ```

. (no comma)
here and in other instances, replace I guess "([a-zA-Z]+) :" with "\0:"
___
*[pmemkv/pmemkv.py, line 116 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-AR-oAC-fQBdBoFPjm:-M-AR-oAC-fQBdBoFPjn:bb0yb96) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/pmemkv.py#L116)):*
> ```Python
>         ----------
>         key : str
>             sets the upper bound for querying.
> ```

lower bound
___
*[pmemkv/pmemkv.py, line 118 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-AQ1eb4WzCQz-TQVBz:-M-AQ1eb4WzCQz-TQVC-:b-e7pf29) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/pmemkv.py#L118)):*
> ```Python
>             sets the upper bound for querying.
>         func : function (may be lambda)
>             Function to be called for each element. Key passed to func is read
> ```

.
(same issue as above... and the same below in other instances of descriptions for 'func')
___
*[pmemkv/pmemkv.py, line 118 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-AQwGk7O-QFvwDEfLY:-M-AQwGk7O-QFvwDEfLZ:b-lrv9ue) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/pmemkv.py#L118)):*
> ```Python
>             sets the upper bound for querying.
>         func : function (may be lambda)
>             Function to be called for each element. Key passed to func is read
> ```

for each **key above** (I guess)
___
*[pmemkv/pmemkv.py, line 133 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-AR8Ag7GbHz2U4Jqhs:-M-AR8Ag7GbHz2U4Jqht:b-51dya4) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/pmemkv.py#L133)):*
> ```Python
>         key : str
>             sets the upper bound for querying.
>       [...]

2020-02-04 14:01 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/25)* status: all files reviewed, 33 unresolved discussions (waiting on @igchor and @karczex)

___
*[pmemkv/kvengine.cc, line 139 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-FUlR04RnJC5dwoFSK:-M-FUlR04RnJC5dwoFSL:b-s4iopl) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/kvengine.cc#L139)):*
> ```cpp
> static int PmemkvValueBuffer_init(PmemkvValueBufferObject *self)
> {
> 	if (self != NULL) {
> ```

I know this is not part of this PR, but I think we could do some improvements with error handling:

what if it is null? maybe return some non-zero value? throw an exception?
___
*[pmemkv/kvengine.cc, line 221 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-FV2678PLDVA2aY8g4:-M-FV2678PLDVA2aY8g5:b-6hc3e) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/kvengine.cc#L221)):*
> ```cpp
> static int Pmemkv_init(PmemkvObject *self)
> {
> 	if (self != NULL) {
> ```

what if it is null? maybe return some non-zero value? throw an exception?
___
*[pmemkv/kvengine.cc, line 282 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-FV7yB1854l1d3qKMq:-M-FV7yB1854l1d3qKMr:b-6hc3e) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/kvengine.cc#L282)):*
> ```cpp
> 		entry->length = valuebyte;
> 		PyObject *args = PyTuple_New(1);
> 		if (args != NULL) {
> ```

what if it is null? maybe return some non-zero value? throw an exception?


<!-- Sent from Reviewable.io -->

2020-02-11 12:46 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/25)* status: 0 of 2 files reviewed, 32 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-ATXwo7IZnba4YoH_k:-M-KtuY87WmUK0wu2zB5:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

1. commit message:
- parameters (lowercase)
- compliant (typo)

2. commit message:
- to be **the best** solution
- **the** creation
</blockquote></details>

Done.

---
___
*[pmemkv/kvengine.cc, line 58 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-AM4uvEcW1SSzGnAF0:-M-KgSHR9H-n1WPUAuMb:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/kvengine.cc#L58)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

happend
</blockquote></details>

Done.
___
*[pmemkv/kvengine.cc, line 76 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-AMgJf5-ZCUkQ08jbc:-M-Kf06EAMCjwO7t4MC_:bnetoc6) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/kvengine.cc#L76)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

1. is it an unexpected way?  compare with https://pmem.io/pmemkv/master/manpages/libpmemkv.3.html
2. in **an** unexp..
</blockquote></details>

In bindings, which provides functionality of forwarding exceptions thrown in callback, such situation is unexpected. If you disagree, please show me the case.
___
*[pmemkv/kvengine.cc, line 88 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-AN4xLA-Yn9Mw_pyC6:-M-imYtI3sgCCqcbwF-l:b-5u3qla) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/kvengine.cc#L88)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I guess we don't implement defrag func. yet...? (we're missing here one status from the latest release)
</blockquote></details>

We are not implementing defrag functionality now. In current pmemkv implementation only explicit call to defrag function in cmap may return DEFRAG_ERROR. 
If defrag is needed for incoming release, exception for it would be implemented in seperate PR
___
*[pmemkv/kvengine.cc, line 139 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-FUlR04RnJC5dwoFSK:-M-intni9V0BdyySHz21:bitqaa2) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/kvengine.cc#L139)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I know this is not part of this PR, but I think we could do some improvements with error handling:

what if it is null? maybe return some non-zero value? throw an exception?
</blockquote></details>

I agree some improvement should be done here. Let's fix it as separate PR. 
___
*[pmemkv/kvengine.cc, line 282 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-FV7yB1854l1d3qKMq:-M-ioHiD5Zkq-b-21DoH:bitqaa2) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/kvengine.cc#L282)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

what if it is null? maybe return some non-zero value? throw an exception?
</blockquote></details>

I agree some improvement should be done here. Let's fix it as separate PR. 
___
*[pmemkv/pmemkv.py, line 43 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-AOarnECwmxJ8sQP7W:-M-Ku3Ks9c5TXJBTAPI7:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/pmemkv.py#L43)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

**n**ame (lowercase)
</blockquote></details>

Done.
___
*[pmemkv/pmemkv.py, line 44 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-AOh445KbNku457V2M:-M-KhOAm18PnPE-IgAcK:bcnq3r1) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/pmemkv.py#L44)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

confi**g:** ... (no space)
</blockquote></details>

Almost good catch :)
there should be space on every argument
___
*[pmemkv/pmemkv.py, line 45 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-9sTj72pumFmeYGY0p:-M-iozhLA4fO9ez0Sdhy:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/pmemkv.py#L45)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

maybe some reference to manpage where all those parameters are described?
</blockquote></details>

Done.
___
*[pmemkv/pmemkv.py, line 88 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-9sKrZ0FfzLKGadeJj:-M-KuG0K5U_SliPWrX4s:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/pmemkv.py#L88)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why not also "or byte-like object"?
</blockquote></details>

Done.
___
*[pmemkv/pmemkv.py, line 101 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-AP8FS08yQK8x0czhZ:-M-KuFFT2koHdItvMVyC:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/pmemkv.py#L101)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

. (no space)
</blockquote></details>

Done.
___
*[pmemkv/pmemkv.py, line 102 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-APEdlEM7_8UkoIvsf:-M-Kx9i10Ym_XoSMNQt2:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/pmemkv.py#L102)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

read**-**only
</blockquote></details>

Done.
___
*[pmemkv/pmemkv.py, line 102 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-AQqXL7NU-mFQxwvaQ:-M-Kur4C4srjpQyalFKt:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/pmemkv.py#L102)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

for each **key** (instead of 'element')
</blockquote></details>

Done.
___
*[pmemkv/pmemkv.py, line 103 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-APLOG01Zd-z3utBuF:-M-Kv0esAnLsj2N6tIEh:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/pmemkv.py#L103)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

function**.** (full stop instead of comma)
</blockquote></details>

Done.
___
*[pmemkv/pmemkv.py, line 103 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-ASEBL-YQpThPtp3sp:-M-Kv4Rp1qGZPxV8SWfS:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/pmemkv.py#L103)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

no comma before "and"
</blockquote></details>

Done.
___
*[pmemkv/pmemkv.py, line 104 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-APPMB4Zru8phmYRC5:-M-irEE84LD4tiNKQKSu:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/pmemkv.py#L104)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

1. accept (typo)
2. "one argument" - what argument?
</blockquote></details>

Done.
___
*[pmemkv/pmemkv. [...]

2020-02-11 14:24 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/25)* status: 0 of 2 files reviewed, 32 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[pmemkv/pmemkv.py, line 115 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-9tAtWE7WW-X3gd_ZK:-M-obyqpDvIc2zxicLaq:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/pmemkv.py#L115)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please add info how strings are converted to binary data (and that the comparison works on binary data)
</blockquote></details>

Done.
___
*[pmemkv/pmemkv.py, line 215 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-ARsS-0mXRbc9ExhZX:-M-ocDeaBjuDwkuR1Fdq:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/pmemkv.py#L215)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

1. in the datastore
and again, in here and in other instances:
2. **N**umber
3. keys.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-02-11 14:58 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/25)* status: 0 of 2 files reviewed, 32 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[pmemkv/pmemkv.py, line 115 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-APcJOCMTiqORhQPiT:-M-okQ2LC0prVZrFw_-M:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/pmemkv.py#L115)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

. (no comma)
here and in other instances, replace I guess "([a-zA-Z]+) :" with "\0:"
</blockquote></details>

Done.
___
*[pmemkv/pmemkv.py, line 118 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-AQ1eb4WzCQz-TQVBz:-M-okRVp0PCI1bXJYE7H:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/pmemkv.py#L118)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
(same issue as above... and the same below in other instances of descriptions for 'func')
</blockquote></details>

Done.
___
*[pmemkv/pmemkv.py, line 133 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-AR8Ag7GbHz2U4Jqhs:-M-okUuXDAdzqmkXXObU:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/pmemkv.py#L133)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
all same issues
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-02-11 15:31 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/25)* status: all files reviewed, 10 unresolved discussions (waiting on @igchor and @karczex)

___
*[pmemkv/kvengine.cc, line 58 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-AM4uvEcW1SSzGnAF0:-M-onc_B2y8SpvgGJDhg:b-cbiwd) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/kvengine.cc#L58)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nope ;)
___
*[pmemkv/pmemkv.py, line 46 at r3](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-opsInAMPwsiKsj7Z0:-M-opsInAMPwsiKsj7Z1:bm813x0) ([raw file](https://github.com/pmem/pmemkv-python/blob/05fe44ac9e56c9d01a8bea207a87f1bc7ea195a4/pmemkv/pmemkv.py#L46)):*
> ```Python
>         config : dict
>             Dictionary with parameters specified for the engine. Required
>             configuration paramteters are dependent on praticular engine.
> ```

"paramteters" ;)
"praticular"
___
*[pmemkv/pmemkv.py, line 142 at r3](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-oqcXi-djWq8zHEuhU:-M-oqcXi-djWq8zHEuhV:b-99u8au) ([raw file](https://github.com/pmem/pmemkv-python/blob/05fe44ac9e56c9d01a8bea207a87f1bc7ea195a4/pmemkv/pmemkv.py#L142)):*
> ```Python
>             Sets the upper bound for querying.
>         func : function (may be lambda)
>             Function to be called for each element. Key passed to func is
> ```

element -> key (below specified key...)
___
*[pmemkv/pmemkv.py, line 246 at r3](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-orBBJ771G2LbQXjWC:-M-orBBJ771G2LbQXjWD:bclrc3) ([raw file](https://github.com/pmem/pmemkv-python/blob/05fe44ac9e56c9d01a8bea207a87f1bc7ea195a4/pmemkv/pmemkv.py#L246)):*
> ```Python
>         ----------
>         func : function (may be lambda)
>             Function to be called for each key/value pair in datastore.
> ```

the datastore
___
*[pmemkv/pmemkv.py, line 267 at r3](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-orNSJ280DXONwsZDL:-M-orNSJ280DXONwsZDM:bcmi6jx) ([raw file](https://github.com/pmem/pmemkv-python/blob/05fe44ac9e56c9d01a8bea207a87f1bc7ea195a4/pmemkv/pmemkv.py#L267)):*
> ```Python
>             Key and value passed to func are read-only buffers and may be accessed
>             by memoryview function. Callback function should accept two positional
>             arguments.
> ```

arguments, which are...

please fix here and in other instances


<!-- Sent from Reviewable.io -->

2020-02-11 15:51 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/25)* status: 0 of 2 files reviewed, 10 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[pmemkv/kvengine.cc, line 58 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-AM4uvEcW1SSzGnAF0:-M-ou9uy5dgaJ1cFKLNB:b-cf4ad6) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/kvengine.cc#L58)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

nope ;)
</blockquote></details>

Much better now. 
___
*[pmemkv/kvengine.cc, line 221 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-FV2678PLDVA2aY8g4:-M-ioEqaEIW5bSAziybz:bitqaa2) ([raw file](https://github.com/pmem/pmemkv-python/blob/5c7a82dad218faa42330a9e50b707b5c531d89bf/pmemkv/kvengine.cc#L221)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

what if it is null? maybe return some non-zero value? throw an exception?
</blockquote></details>

I agree some improvement should be done here. Let's fix it as separate PR. 
___
*[pmemkv/pmemkv.py, line 46 at r3](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-opsInAMPwsiKsj7Z0:-M-otWUkA26KtmQBHvLW:b-fnt22w) ([raw file](https://github.com/pmem/pmemkv-python/blob/05fe44ac9e56c9d01a8bea207a87f1bc7ea195a4/pmemkv/pmemkv.py#L46)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

"paramteters" ;)
"praticular"
</blockquote></details>

done :) 
___
*[pmemkv/pmemkv.py, line 142 at r3](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-oqcXi-djWq8zHEuhU:-M-ougDH5Ry8qd6QZRKi:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/05fe44ac9e56c9d01a8bea207a87f1bc7ea195a4/pmemkv/pmemkv.py#L142)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

element -> key (below specified key...)
</blockquote></details>

Done.
___
*[pmemkv/pmemkv.py, line 246 at r3](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-orBBJ771G2LbQXjWC:-M-oth4LByVIvBneaINP:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/05fe44ac9e56c9d01a8bea207a87f1bc7ea195a4/pmemkv/pmemkv.py#L246)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

the datastore
</blockquote></details>

Done.
___
*[pmemkv/pmemkv.py, line 267 at r3](https://reviewable.io/reviews/pmem/pmemkv-python/25#-M-orNSJ280DXONwsZDL:-M-ov7NBBo-LvpOev-tQ:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/05fe44ac9e56c9d01a8bea207a87f1bc7ea195a4/pmemkv/pmemkv.py#L267)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

arguments, which are...

please fix here and in other instances
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-02-12 14:47 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/25#-:-M-trgRE2EURviRlq9p4:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @igchor)



<!-- Sent from Reviewable.io -->

2020-02-12 14:59 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/25#-:-M-tuMPDB4xuufuzdYub:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-02-12 15:27 UTC, merged